spring.application.name=StarPassAPI

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/starpass}
spring.datasource.username=starpass
spring.datasource.password=123
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create-drop

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=starpass
spring.rabbitmq.password=123